# Generated by Django 4.2.28 on 2026-03-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rescue_app', '0003_alter_notification_id_alter_petreport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='petreport',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
