# Generated by Django 4.2.28 on 2026-03-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rescue_app', '0004_petreport_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='petreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
