# Generated by Django 6.0.3 on 2026-03-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rescue_app', '0005_petreport_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='petreport',
            name='pet_image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_reports/'),
        ),
    ]
