# Generated by Django 6.0.3 on 2026-03-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rescue_app', '0006_petreport_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petreport',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='petreport',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='petreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petreport',
            name='pet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
