# Generated by Django 6.0.3 on 2026-03-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rescue_app', '0007_alter_petreport_breed_alter_petreport_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petreport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='petreport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
