# Generated by Django 6.0.3 on 2026-03-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_rescue_app', '0008_petreport_latitude_petreport_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petreport',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='petreport',
            name='longitude',
        ),
    ]
